### ISSUE TITLE
设置屏保时间无效，不能进入屏保

### ISSUE THREAD

**Issue by CrossCC** [ukui/ukui-session-manager#13]
版本: 20.04LTS
iso：ubuntukylin-ukui3.0-2020022402-amd64.iso
测试环境：兆芯E台式机

测试步骤：
1. 设置，个性化，屏保
2. 更改等待时间为1分钟，并确保开启屏保为开的状态

预期结果：静置电脑1分钟后进入黑屏屏保。

实际结果：1分钟不操作电脑，没有进入屏保。

**Comment by ll-eleven** [comment]
3e92f126f4fc4110b4e8d0709cff4aa4e387e147  已在这次提交中解决

**Comment by xiaodongliu-nudt** [comment]
20200327版本通过
