### ISSUE TITLE
在Ctrl+alt+delete界面，执行alt+tab，窗口切换程序显示在session manager之上

### ISSUE THREAD

**Issue by liumin0322** [ukui/ukui-session-manager#22]

**Comment by liumin0322** [comment]
![2020-04-07 20-46-02屏幕截图](https://user-images.githubusercontent.com/48200161/78670746-d187d880-7910-11ea-81b2-8ccc9bcabfa9.png)

**Comment by ll-eleven** [comment]
This has been resolved in commit 649219b28b8e1750205a76525b2b05dc6cc346c0

**Comment by ikeyhzj** [comment]
新版本已经解决
