### ISSUE TITLE
Logout time is too long

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-session-manager#24]
Version: 20.04LTS
Iso: ubuntukylin-ukui3.0-20200410-amd64.iso
Test environment: Lenovo Qitian M415-N000 desktop
Test steps:
1.Ctrl + Alt + Delete log off or power off
2.
Expected result: logout completed within seconds
Actual result: logout time 20 seconds

**Comment by ll-eleven** [comment]
this has been resolved in commit b82ea6d784b2a2ae2b9de170864fc3139347f850

**Comment by ikeyhzj** [comment]
最新版本已经解决
