### ISSUE TITLE
Ctrl+Alt+delete快捷键报错

### ISSUE THREAD

**Issue by MeganHemh** [ukui/ukui-session-manager#5]
2004 按Ctrl+Alt+delete 不能锁屏，弹框提示"无法执行命令:ukui-session-save--logout-dialog",请检查此命令是否有效

**Comment by ll-eleven** [comment]
ukui-settings-daemon 中快捷键设置没更新，现在已经解决

**Comment by xiaodongliu-nudt** [comment]
20200327版本解决
